class MarksmanshipV2 < ActiveRecord::Migration
  def change
    Changelog.find_or_create_by(fp_type: 'Marksmanship Hunter', version: 2).update_attributes(content: '<ul><li>Tracks the amount of Focus gained/wasted throughout the fight.</li><li>Tracks the total number of Aimed Shots possible, by calculating the amount of Focus left over after casting your other key spells, in addition to your Lock and Load procs.</li><li>Tracks incorrect uses of Aimed Shot. Aimed Shot should only be used when the target is Vulnerable, or if you would cap Focus otherwise.</li><li>Copies of Aimed Shot generated by Legacy of the Windrunners are counted as a separate cast.</li><li>Added Bullseye to the cooldowns timeline</li></ul>');
  end
end
